### ISSUE TITLE
StringIndexOutOfBoundsException when parsing "<strong>\t</strong>"

### ISSUE THREAD

**Issue by eziztm** [vsch/flexmark-java#149]
StringIndexOutOfBoundsException  is thrown whenever "<strong>\t</strong>" or any other element with only \t inside is parsed.

> 	at java.lang.String.charAt(String.java:658)
	at com.vladsch.flexmark.convert.html.FlexmarkHtmlParser.wrapTextNodes(FlexmarkHtmlParser.java:437)
	at com.vladsch.flexmark.convert.html.FlexmarkHtmlParser.processStrong(FlexmarkHtmlParser.java:714)
	at com.vladsch.flexmark.convert.html.FlexmarkHtmlParser.processElement(FlexmarkHtmlParser.java:305)
	at com.vladsch.flexmark.convert.html.FlexmarkHtmlParser.processHtmlTree(FlexmarkHtmlParser.java:271)
	at com.vladsch.flexmark.convert.html.FlexmarkHtmlParser.parse(FlexmarkHtmlParser.java:148)
	at com.vladsch.flexmark.convert.html.FlexmarkHtmlParser.parse(FlexmarkHtmlParser.java:225)

>

**Comment by vsch** [comment]
@eziztm, thank you for the report. Sorry for the slow reply. This one slipped through the cracks.

Fix to be released shortly.

**Comment by vsch** [comment]
fixed in 0.27.4
