### ISSUE TITLE
Rendering Error - Illegal Character

### ISSUE THREAD

**Issue by borisdiakur** [vsch/flexmark-java#246]
When trying to render the following Markdown page from github, flexmark-java throws an error:

URL: https://raw.githubusercontent.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/master/README.md

Illegal character in path at index 43: http://download.ahnlab.com/kr/site/library/[Report]Andariel_Threat_Group.pdf

See https://github.com/borisdiakur/marked/issues/17

**Comment by borisdiakur** [comment]
This is how my code looks like right now:

```java
String convertToHtml(String markdown, URL currentURL) {
        MutableDataSet options = new MutableDataSet();
        options.set(Parser.EXTENSIONS, Arrays.asList(TablesExtension.create(), StrikethroughExtension.create(),
                ConfluenceCodeBlockExtension.create()));
        Parser parser = Parser.builder(options).build();
        Builder builder = HtmlRenderer.builder(options);
        builder.percentEncodeUrls(true);
        if (currentURL != null) {
            builder.linkResolverFactory(new RelativeResolverFactory(currentURL));
        }
        HtmlRenderer renderer = builder.build();
        return renderer.render(parser.parse(markdown));
    }
```

My unit test is green:

```java
@Test
    public void encodesUrls() {
        // given a markdown containing code fence
        String markdown = "[[Qux] Baz](http://example.com/[yolo]foobar.pdf)";

        // when converting markdown to html
        String html = markedMacro.convertToHtml(markdown);

        // then code tag is wrapped in confluence blocks
        String expectedHtml = "<p><a href=\"http://example.com/%5Byolo%5Dfoobar.pdf\">[Qux] Baz</a></p>\n";

        assertEquals(expectedHtml, html);
    }
```

But I’m still getting the same error: 
<img width="656" alt="screen shot 2018-07-14 at 23 13 01" src="https://user-images.githubusercontent.com/527049/42728480-8865268c-87bb-11e8-91be-fa76322c9e75.png">

Here is the full stack trace:

```shell
[INFO] [talledLocalContainer] java.lang.IllegalArgumentException: Illegal character in path at index 43: http://download.ahnlab.com/kr/site/library/[Report]Andariel_Threat_Group.pdf
[INFO] [talledLocalContainer] 	at java.net.URI.create(URI.java:852)
[INFO] [talledLocalContainer] 	at java.net.URI.resolve(URI.java:1036)
[INFO] [talledLocalContainer] 	at com.borisdiakur.marked.RelativeResolverFactory$RelativeLinkResolver.resolveLink(RelativeResolverFactory.java:52)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.html.HtmlRenderer$MainNodeRenderer.resolveLink(HtmlRenderer.java:543)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.html.HtmlRenderer$MainNodeRenderer.resolveLink(HtmlRenderer.java:522)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.html.renderer.CoreNodeRenderer.render(CoreNodeRenderer.java:669)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.html.renderer.CoreNodeRenderer.access$2000(CoreNodeRenderer.java:27)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.html.renderer.CoreNodeRenderer$21.render(CoreNodeRenderer.java:175)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.html.renderer.CoreNodeRenderer$21.render(CoreNodeRenderer.java:172)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.html.renderer.NodeRenderingHandler.render(NodeRenderingHandler.java:16)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.html.HtmlRenderer$MainNodeRenderer.renderNode(HtmlRenderer.java:666)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.html.HtmlRenderer$MainNodeRenderer.renderChildrenNode(HtmlRenderer.java:682)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.html.HtmlRenderer$MainNodeRenderer.renderChildren(HtmlRenderer.java:674)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.html.renderer.CoreNodeRenderer.renderTextBlockParagraphLines(CoreNodeRenderer.java:416)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.html.renderer.CoreNodeRenderer.render(CoreNodeRenderer.java:433)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.html.renderer.CoreNodeRenderer.access$2600(CoreNodeRenderer.java:27)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.html.renderer.CoreNodeRenderer$27.render(CoreNodeRenderer.java:211)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.html.renderer.CoreNodeRenderer$27.render(CoreNodeRenderer.java:208)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.html.renderer.NodeRenderingHandler.render(NodeRenderingHandler.java:16)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.html.HtmlRenderer$MainNodeRenderer.renderNode(HtmlRenderer.java:666)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.html.HtmlRenderer$MainNodeRenderer.renderChildrenNode(HtmlRenderer.java:682)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.html.HtmlRenderer$MainNodeRenderer.renderChildren(HtmlRenderer.java:674)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.html.renderer.CoreNodeRenderer$39.run(CoreNodeRenderer.java:392)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.util.html.HtmlFormattingAppendableBase.tag(HtmlFormattingAppendableBase.java:279)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.util.html.HtmlFormattingAppendableBase.tagLine(HtmlFormattingAppendableBase.java:327)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.html.renderer.CoreNodeRenderer.renderListItem(CoreNodeRenderer.java:388)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.html.renderer.CoreNodeRenderer.render(CoreNodeRenderer.java:379)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.html.renderer.CoreNodeRenderer.access$2200(CoreNodeRenderer.java:27)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.html.renderer.CoreNodeRenderer$23.render(CoreNodeRenderer.java:187)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.html.renderer.CoreNodeRenderer$23.render(CoreNodeRenderer.java:184)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.html.renderer.NodeRenderingHandler.render(NodeRenderingHandler.java:16)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.html.HtmlRenderer$MainNodeRenderer.renderNode(HtmlRenderer.java:666)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.html.HtmlRenderer$MainNodeRenderer.renderChildrenNode(HtmlRenderer.java:682)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.html.HtmlRenderer$MainNodeRenderer.renderChildren(HtmlRenderer.java:674)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.html.renderer.CoreNodeRenderer$37.run(CoreNodeRenderer.java:362)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.util.html.HtmlFormattingAppendableBase.tag(HtmlFormattingAppendableBase.java:279)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.util.html.HtmlFormattingAppendableBase.tagIndent(HtmlFormattingAppendableBase.java:333)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.html.renderer.CoreNodeRenderer.render(CoreNodeRenderer.java:359)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.html.renderer.CoreNodeRenderer.access$200(CoreNodeRenderer.java:27)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.html.renderer.CoreNodeRenderer$3.render(CoreNodeRenderer.java:67)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.html.renderer.CoreNodeRenderer$3.render(CoreNodeRenderer.java:64)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.html.renderer.NodeRenderingHandler.render(NodeRenderingHandler.java:16)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.html.HtmlRenderer$MainNodeRenderer.renderNode(HtmlRenderer.java:666)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.html.HtmlRenderer$MainNodeRenderer.renderChildrenNode(HtmlRenderer.java:682)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.html.HtmlRenderer$MainNodeRenderer.renderChildren(HtmlRenderer.java:674)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.html.renderer.CoreNodeRenderer.render(CoreNodeRenderer.java:255)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.html.renderer.CoreNodeRenderer.access$500(CoreNodeRenderer.java:27)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.html.renderer.CoreNodeRenderer$6.render(CoreNodeRenderer.java:85)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.html.renderer.CoreNodeRenderer$6.render(CoreNodeRenderer.java:82)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.html.renderer.NodeRenderingHandler.render(NodeRenderingHandler.java:16)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.html.HtmlRenderer$MainNodeRenderer.renderNode(HtmlRenderer.java:654)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.html.HtmlRenderer$MainNodeRenderer.render(HtmlRenderer.java:615)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.html.HtmlRenderer.render(HtmlRenderer.java:190)
[INFO] [talledLocalContainer] 	at com.vladsch.flexmark.html.HtmlRenderer.render(HtmlRenderer.java:214)
[INFO] [talledLocalContainer] 	at com.borisdiakur.marked.MarkedMacro.convertToHtml(MarkedMacro.java:101)
[INFO] [talledLocalContainer] 	at com.borisdiakur.marked.MarkedMacro.execute(MarkedMacro.java:83)

```

**Comment by vsch** [comment]
@borisdiakur, the URL encoding is done after the link resolver has done its processing.

When you pass the link to URI.resolve you should URL encode the link. If you do URL encoding of the resolved link url returned from your link resolver then you should turn off the `HtmlRenderer.PERCENT_ENCODE_URLS` since you do that in your link resolver.

You can use the library code to encode the URL if you want: `Escaping.percentEncodeUrl(resolvedLink.getUrl())`

This is the reason why the percent URL encoding is turned off by default because it will be usually done by the link resolver.
