### ISSUE TITLE
how to solve convertPdf SocketTimeoutException ？

### ISSUE THREAD

**Issue by AlexChensm** [vsch/flexmark-java#350]
when i want to convert md that has the url that is unable to requested ,  the exportToPdf function will try to request this url all the time; so the program happend  socketTimeoutException。
here is the exception:
IO problem for https://img.shields.io/bower/v/editor.md.svg
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at java.net.URL.openStream(URL.java:1045)
	at com.openhtmltopdf.swing.NaiveUserAgent$DefaultHttpStreamFactory.getUrl(NaiveUserAgent.java:131)
	at com.openhtmltopdf.swing.NaiveUserAgent.openStream(NaiveUserAgent.java:215)
	at com.openhtmltopdf.pdfboxout.PdfBoxUserAgent.getImageResource(PdfBoxUserAgent.java:84)
	at com.openhtmltopdf.pdfboxout.PdfBoxReplacedElementFactory.createReplacedElement(PdfBoxReplacedElementFactory.java:65)
	at com.openhtmltopdf.render.BlockBox.calcMinMaxWidth(BlockBox.java:1581)
	at com.openhtmltopdf.render.BlockBox.calcShrinkToFitWidth(BlockBox.java:1501)
	at com.openhtmltopdf.render.BlockBox.calcShrinkToFitWidthIfNeeded(BlockBox.java:976)
	at com.openhtmltopdf.render.BlockBox.layout(BlockBox.java:869)
	at com.openhtmltopdf.render.BlockBox.layout(BlockBox.java:823)
	at com.openhtmltopdf.layout.InlineBoxing.layoutInlineBlockContent(InlineBoxing.java:426)
	at com.openhtmltopdf.layout.InlineBoxing.layoutContent(InlineBoxing.java:317)
	at com.openhtmltopdf.render.BlockBox.layoutInlineChildren(BlockBox.java:1068)
	at com.openhtmltopdf.render.BlockBox.layoutChildren(BlockBox.java:1049)
	at com.openhtmltopdf.render.BlockBox.layout(BlockBox.java:906)
	at com.openhtmltopdf.render.BlockBox.layout(BlockBox.java:823)
	at com.openhtmltopdf.layout.BlockBoxing.layoutBlockChild0(BlockBoxing.java:321)
	at com.openhtmltopdf.layout.BlockBoxing.layoutBlockChild(BlockBoxing.java:299)
	at com.openhtmltopdf.layout.BlockBoxing.layoutContent(BlockBoxing.java:90)
	at com.openhtmltopdf.render.BlockBox.layoutChildren(BlockBox.java:1052)
	at com.openhtmltopdf.render.BlockBox.layout(BlockBox.java:906)
	at com.openhtmltopdf.render.BlockBox.layout(BlockBox.java:823)
	at com.openhtmltopdf.layout.BlockBoxing.layoutBlockChild0(BlockBoxing.java:321)
	at com.openhtmltopdf.layout.BlockBoxing.layoutBlockChild(BlockBoxing.java:299)
	at com.openhtmltopdf.layout.BlockBoxing.layoutContent(BlockBoxing.java:90)
	at com.openhtmltopdf.render.BlockBox.layoutChildren(BlockBox.java:1052)
	at com.openhtmltopdf.render.BlockBox.layout(BlockBox.java:906)
	at com.openhtmltopdf.render.BlockBox.layout(BlockBox.java:823)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.layout(PdfBoxRenderer.java:333)
	at com.vladsch.flexmark.pdf.converter.PdfConverterExtension.exportToPdf(PdfConverterExtension.java:123)
	at com.vladsch.flexmark.pdf.converter.PdfConverterExtension.exportToPdf(PdfConverterExtension.java:93)
	at com.vladsch.flexmark.pdf.converter.PdfConverterExtension.exportToPdf(PdfConverterExtension.java:83)
	at com.newland.bomc.docmange.utils.MdConvertUtil.convertPdf(MdConvertUtil.java:101)
	at com.newland.bomc.docmange.utils.MdConvertUtil.main(MdConvertUtil.java:193)

in the end , it will happend out of memory；
so how to solve this problem?
                                                                                                                         Thanks a lot

**Comment by vsch** [comment]
@AlexChensm, the error occurs deep in HTML to PDF library so the only solution I can see is to load images in a Custom Link Resolver and replace the URL to the downloaded file. In case of error an generic error image can be substituted.
