### ISSUE TITLE
Enable proguard to obfuscate and report errors

### ISSUE THREAD

**Issue by GXSZone** [vsch/flexmark-java#442]
Crash information:
`No enum constant e.q.a.f.j.n.a.a
`
type:java.lang.IllegalArgumentException

full detail:
```
java.lang.IllegalArgumentException: No enum constant e.q.a.f.j.n.a.a
	at java.lang.Enum.valueOf(Enum.java:257)
	at e.q.a.f.h.m0$d.a(BitFieldSet.java:8)
	at e.q.a.f.h.m0.t(BitFieldSet.java:1)
	at e.q.a.f.h.m0.B(BitFieldSet.java:2)
	at e.q.a.f.h.m0.D(BitFieldSet.java:1)
	at e.q.a.f.j.n.<clinit>(LineAppendable.java:8)
	at e.q.a.d.j.<clinit>(HtmlRenderer.java:53)
```

Here are two packs `com.vladsch.flexmark.util.misc`  and `com.vladsch.flexmark.util.sequence` 
Enum problem

**Comment by saket** [comment]
These proguard rules seem to work for me with `v0.64.8`:

```
# flexmark's BitFieldSet reflects over these enums and reconstructs constants using
# Enum.valueOf(field.getName()), so their constant names must survive obfuscation.
-keepclassmembernames class com.vladsch.flexmark.util.sequence.BasedOptionsHolder$Options {
    <fields>;
}
-keepclassmembernames class com.vladsch.flexmark.util.sequence.LineAppendable$Options {
    <fields>;
}
-keepclassmembernames class com.vladsch.flexmark.util.sequence.LineInfo$Flags {
    <fields>;
}
-keepclassmembernames class com.vladsch.flexmark.util.sequence.builder.ISegmentBuilder$Options {
    <fields>;
}
```
