### ISSUE TITLE
Fatal Exception: java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by TinaT2** [vsch/flexmark-java#470]
```
//Error title: 
Fatal Exception:
 java.lang.NoClassDefFoundError
com.vladsch.flexmark.util.data.DataKey$$ExternalSyntheticLambda1
//Error message: 
com.vladsch.flexmark.util.data.DataKey.<init> (DataKey.java:69)
com.vladsch.flexmark.util.data.SharedDataKeys.<clinit> (SharedDataKeys.java:10)
com.vladsch.flexmark.parser.Parser.<clinit> (Parser.java:37)
de.netalic.messenger.util.MessengerUtil.textWithMarkdown (MessengerUtil.kt:17)
...
```
Andriod SDK 6, API 23

**Comment by Moriafly** [comment]
I'm also having this issue on Android 6, I've tried many ways but none of them work. Is there a solution please?

**Comment by Moriafly** [comment]
java.lang.NoClassDefFoundError: com.vladsch.flexmark.util.data.DataKey$$ExternalSyntheticLambda2
        at com.vladsch.flexmark.util.data.DataKey.<init>(DataKey.java:69)
        at com.vladsch.flexmark.ext.tables.TablesExtension.<clinit>(TablesExtension.java:29)
